spring.application.name=demo
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5:3b
spring.ai.ollama.chat.options.temperature=0.8
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true